# Generated by Django 6.1 on 2026-09-09 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., DPA-2012-01', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('ACCOUNTS', 'Accounts'), ('RESIDENTS', 'Residents'), ('PEOPLE', 'People'), ('PROPERTIES', 'Properties'), ('VISITORS', 'Visitors'), ('SECURITY', 'Security'), ('VEHICLES', 'Vehicles'), ('FACILITIES', 'Facilities'), ('PAYMENTS', 'Payments'), ('ANNOUNCEMENTS', 'Announcements'), ('NOTIFICATIONS', 'Notifications'), ('COMPLIANCE', 'Compliance'), ('SYSTEM', 'System')], max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('module', models.CharField(choices=[('AUTH', 'Authentication'), ('ACCOUNTS', 'Accounts'), ('RESIDENTS', 'Residents'), ('PEOPLE', 'People'), ('PROPERTIES', 'Properties'), ('VISITORS', 'Visitors'), ('SECURITY', 'Security'), ('VEHICLES', 'Vehicles'), ('FACILITIES', 'Facilities'), ('PAYMENTS', 'Payments'), ('ANNOUNCEMENTS', 'Announcements'), ('NOTIFICATIONS', 'Notifications'), ('COMPLIANCE', 'Compliance'), ('SYSTEM', 'System')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('ACTION_REQUIRED', 'Action Required'), ('REMEDIATION', 'Remediation'), ('VERIFICATION', 'Verification'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=30)),
                ('description', models.TextField()),
                ('required_action', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_compliance_findings', to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='audit.compliancecontrol')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compliance_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='compliance_evidence/%Y/%m/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='audit.compliancefinding')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.TextField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='audit.compliancefinding')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('AUTH', 'Authentication'), ('ACCOUNTS', 'Accounts'), ('RESIDENTS', 'Residents'), ('PEOPLE', 'People'), ('PROPERTIES', 'Properties'), ('VISITORS', 'Visitors'), ('SECURITY', 'Security'), ('VEHICLES', 'Vehicles'), ('FACILITIES', 'Facilities'), ('PAYMENTS', 'Payments'), ('ANNOUNCEMENTS', 'Announcements'), ('NOTIFICATIONS', 'Notifications'), ('COMPLIANCE', 'Compliance'), ('SYSTEM', 'System')], db_index=True, max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Failed Login'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CANCEL', 'Cancel'), ('SUBMIT', 'Submit'), ('VERIFY', 'Verify'), ('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('SECURITY_CLEARANCE', 'Security Clearance'), ('START', 'Start'), ('COMPLETE', 'Complete'), ('INSPECT', 'Inspect'), ('REFUND', 'Refund'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_CHANGE', 'Role Change'), ('EXPORT', 'Export'), ('IMPORT', 'Import')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('object_type', models.CharField(blank=True, default='', max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('request_method', models.CharField(blank=True, default='', max_length=10)),
                ('request_path', models.CharField(blank=True, default='', max_length=500)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'created_at'], name='audit_audit_module_8d996c_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_0c0ad1_idx'), models.Index(fields=['severity', 'created_at'], name='audit_audit_severit_772df7_idx'), models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_39eebe_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__0e78a5_idx')],
            },
        ),
    ]
