# Generated by Django 6.1 on 2026-09-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditevent',
            name='audit_audit_module_8d996c_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditevent',
            name='audit_audit_action_0c0ad1_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditevent',
            name='audit_audit_severit_772df7_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditevent',
            name='audit_audit_user_id_39eebe_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditevent',
            name='audit_audit_object__0e78a5_idx',
        ),
        migrations.RemoveField(
            model_name='compliancefinding',
            name='control',
        ),
        migrations.RemoveField(
            model_name='complianceevidence',
            name='finding',
        ),
        migrations.RemoveField(
            model_name='complianceevidence',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='compliancefinding',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='compliancefinding',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='correctiveaction',
            name='finding',
        ),
        migrations.RemoveField(
            model_name='correctiveaction',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='ComplianceControl',
        ),
        migrations.DeleteModel(
            name='ComplianceEvidence',
        ),
        migrations.DeleteModel(
            name='ComplianceFinding',
        ),
        migrations.DeleteModel(
            name='CorrectiveAction',
        ),
        migrations.DeleteModel(
            name='AuditEvent',
        ),
    ]
