# Generated by Django 6.1 on 2026-09-10 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0002_remove_auditevent_audit_audit_module_8d996c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_role', models.CharField(choices=[('ADMIN', 'Administrator'), ('SECURITY', 'Security'), ('RESIDENT', 'Resident'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=30)),
                ('module', models.CharField(choices=[('ACCOUNTS', 'Accounts'), ('RESIDENTS', 'Residents'), ('PROPERTIES', 'Properties'), ('VISITORS', 'Visitors'), ('VEHICLES', 'Vehicles'), ('SECURITY', 'Security'), ('FACILITIES', 'Facilities'), ('ANNOUNCEMENTS', 'Announcements'), ('NOTIFICATIONS', 'Notifications'), ('AUDIT', 'Audit'), ('SYSTEM', 'System')], db_index=True, max_length=40)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('VIEW', 'View'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('VERIFY', 'Verify'), ('CANCEL', 'Cancel'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('REFUND', 'Refund'), ('CLEARANCE', 'Clearance'), ('INSPECT', 'Inspect'), ('EXPIRE', 'Expire'), ('EXPORT', 'Export'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_CHANGE', 'Role Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('OTHER', 'Other')], db_index=True, max_length=40)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('object_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DENIED', 'Denied')], db_index=True, default='SUCCESS', max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['module', 'action', '-timestamp'], name='audit_event_module_action_ts'), models.Index(fields=['actor', '-timestamp'], name='audit_event_actor_ts'), models.Index(fields=['severity', '-timestamp'], name='audit_event_severity_ts'), models.Index(fields=['result', '-timestamp'], name='audit_event_result_ts'), models.Index(fields=['object_type', 'object_id'], name='audit_event_object_idx')],
            },
        ),
    ]
