# Generated by Django 6.1 on 2026-09-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='request_method',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_path',
            field=models.TextField(blank=True, default=''),
        ),
    ]
