# Generated by Django 6.1 on 2026-08-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active_resident',
            field=models.BooleanField(default=False),
        ),
    ]
