# Generated by Django 6.1 on 2026-08-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('HOMEOWNER', 'Homeowner'), ('TENANT', 'Tenant'), ('SECURITY', 'Security Officer')], default='TENANT', max_length=20),
        ),
    ]
