# Generated by Django 6.1 on 2026-09-03 05:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('facility_type', models.CharField(choices=[('CLUBHOUSE', 'Clubhouse'), ('BASKETBALL_COURT', 'Basketball Court'), ('SWIMMING_POOL', 'Swimming Pool'), ('CHILDREN_PARK', "Children's Park"), ('CAR_PARKING', 'Car Parking')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('parking_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_booking_minutes', models.PositiveIntegerField(default=60)),
                ('maximum_booking_minutes', models.PositiveIntegerField(default=480)),
                ('advance_booking_days', models.PositiveIntegerField(default=30)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_security_deposit', models.BooleanField(default=False)),
                ('security_deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rental_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('resident_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bookable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENCIL', 'Pencil Book'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('IN_USE', 'In Use'), ('COMPLETED', 'Completed'), ('INSPECTION_PENDING', 'Inspection Pending'), ('REFUND_PENDING', 'Refund Pending'), ('CLOSED', 'Closed')], default='PENCIL', max_length=30)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('FAMILY', 'Family'), ('BIRTHDAY', 'Birthday'), ('MEETING', 'Meeting'), ('COMMUNITY_EVENT', 'Community Event'), ('OTHER', 'Other')], default='PERSONAL', max_length=30)),
                ('event_description', models.TextField(blank=True, default='')),
                ('estimated_guests', models.PositiveIntegerField(default=1)),
                ('has_external_supplier', models.BooleanField(default=False)),
                ('supplier_details', models.TextField(blank=True, default='')),
                ('rental_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pencil_created_at', models.DateTimeField(blank=True, null=True)),
                ('pencil_expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('security_clearance_required', models.BooleanField(default=True)),
                ('security_clearance_completed', models.BooleanField(default=False)),
                ('security_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_facility_bookings', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_bookings', to='residents.resident')),
                ('security_cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleared_facility_bookings', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='facilities.facility')),
            ],
            options={
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('DAMAGE_FOUND', 'Damage Found'), ('CLEANUP_REQUIRED', 'Cleanup Required')], default='PENDING', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='facilities.booking')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facility_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=1)),
                ('full_name', models.CharField(max_length=200)),
                ('vehicle_plate_number', models.CharField(blank=True, default='', max_length=30)),
                ('vehicle_model', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='facilities.booking')),
            ],
            options={
                'ordering': ['row_number', 'id'],
                'indexes': [models.Index(fields=['booking', 'row_number'], name='facilities__booking_80f2b4_idx'), models.Index(fields=['vehicle_plate_number'], name='facilities__vehicle_5b7aab_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'row_number'), name='unique_booking_guest_row')],
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=30)),
                ('payment_type', models.CharField(choices=[('BOOKING_TOTAL', 'Facility Booking Total'), ('SECURITY_DEPOSIT_REFUND', 'Security Deposit Refund')], max_length=40)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('GCASH', 'GCash'), ('MAYA', 'Maya'), ('INSTAPAY_QR', 'InstaPay QR'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=30)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], default='INCOMING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('proof', models.FileField(blank=True, null=True, upload_to='facility_bookings/payment_proofs/')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='facilities.booking')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_booking_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'payment_type', 'status'], name='facilities__booking_29c64c_idx'), models.Index(fields=['reference_number'], name='facilities__referen_9fb287_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['facility', 'booking_date', 'status'], name='facilities__facilit_28786a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['resident', '-booking_date'], name='facilities__residen_d88a17_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'pencil_expires_at'], name='facilities__status_5d6bda_idx'),
        ),
    ]
