# Generated by Django 6.1 on 2026-09-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
    ]
