# Generated by Django 6.1 on 2026-09-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_auto_20260903_2055'),
    ]

    operations = [
    ]
