# Generated by Django 6.1 on 2026-09-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_auto_20260904_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('FAMILY', 'Family'), ('BIRTHDAY', 'Birthday'), ('MEETING', 'Meeting'), ('COMMUNITY_EVENT', 'Community Event'), ('OTHERS', 'Others')], default='PERSONAL', max_length=30),
        ),
    ]
