# Generated by Django 6.1 on 2026-09-04 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_add_pencil_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='security_cleared_by',
        ),
        migrations.AddField(
            model_name='booking',
            name='security_cleared_byy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleared_facility_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
