# Generated by Django 6.1 on 2026-09-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_remove_booking_security_cleared_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='security_cleared_byy',
            new_name='security_cleared_by',
        ),
    ]
