# Generated by Django 6.1 on 2026-08-11 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(default='Main Subdivision', max_length=150)),
                ('block', models.CharField(max_length=50)),
                ('lot', models.CharField(max_length=50)),
                ('house_number', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OWNER_OCCUPIED', 'Owner Occupied'), ('TENANT_OCCUPIED', 'Tenant Occupied')], default='VACANT', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['block', 'lot'],
                'constraints': [models.UniqueConstraint(fields=('subdivision', 'block', 'lot'), name='unique_property_location')],
            },
        ),
        migrations.CreateModel(
            name='PropertyOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_type', models.CharField(choices=[('HOMEOWNER', 'Homeowner'), ('TENANT', 'Tenant')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancy_history', to='properties.property')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancy_history', to='residents.resident')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homeowner', models.ForeignKey(limit_choices_to={'role': 'HOMEOWNER'}, on_delete=django.db.models.deletion.PROTECT, related_name='property_ownerships', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_history', to='properties.property')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
