# Generated by Django 6.1 on 2026-08-22 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('NOTICE', 'Notice'), ('MAINTENANCE', 'Maintenance'), ('COMMUNITY_EVENT', 'Community Event'), ('POLICY', 'Policy'), ('SECURITY', 'Security')], default='GENERAL', max_length=30)),
                ('priority', models.CharField(choices=[('INFO', 'Information'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent')], default='INFO', max_length=20)),
                ('audience', models.CharField(choices=[('ALL_RESIDENTS', 'All Residents'), ('HOMEOWNERS', 'Homeowners'), ('TENANTS', 'Tenants')], default='ALL_RESIDENTS', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_announcements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='announcemen_status_7c07df_idx'), models.Index(fields=['audience', 'status', '-published_at'], name='announcemen_audienc_a720c0_idx'), models.Index(fields=['category', 'status', '-published_at'], name='announcemen_categor_be04f5_idx')],
            },
        ),
    ]
