# Generated by Django 6.1 on 2026-08-11 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('residents', '0001_initial'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_home_address', models.CharField(max_length=255)),
                ('visitor_phone', models.CharField(max_length=30)),
                ('visit_date', models.DateField()),
                ('expected_time_in', models.TimeField()),
                ('expected_time_out', models.TimeField()),
                ('host_name_snapshot', models.CharField(max_length=200)),
                ('host_address_snapshot', models.CharField(max_length=255)),
                ('host_phone_snapshot', models.CharField(max_length=30)),
                ('host_type_snapshot', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitor_invitations', to='residents.resident')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitor_invitations', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INSIDE', 'Inside'), ('COMPLETED', 'Completed'), ('DENIED', 'Denied')], default='INSIDE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitor_visits', to='security.gate')),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='visit', to='visitors.visitorinvitation')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scanned_visitor_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_in'],
            },
        ),
    ]
