# Generated by Django 6.1 on 2026-08-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gate_type', models.CharField(choices=[('MAIN_ENTRANCE', 'Main Entrance'), ('SECONDARY', 'Secondary Gate'), ('SERVICE', 'Service Gate'), ('EMERGENCY', 'Emergency Gate')], default='MAIN_ENTRANCE', max_length=30)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
