# Generated by Django 6.1 on 2026-08-11 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('PICKUP', 'Pickup'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('OTHER', 'Other')], max_length=20)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=30, unique=True)),
                ('ownership_type', models.CharField(choices=[('OWNED', 'Owned'), ('COMPANY', 'Company'), ('LEASED', 'Leased'), ('OTHER', 'Other')], default='OWNED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='properties.property')),
                ('registered_resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='residents.resident')),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='MotoristSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('sticker_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_motorist_stickers', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motorist_stickers', to='properties.property')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motorist_stickers', to='residents.resident')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='motorist_sticker', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
